version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8083:8000"
    volumes:
      - "/c/Users/caily/Documents/coding/interactive-docker-tutorial/examples/docker-compose/src:/usr/app"
    working_dir: /usr/app

  db:
    image: mongo:latest
    ports:
      - "27018:27017"